CREATE TABLE FREEBOARD(
SEQ NUMBER NOT NULL,
CATEGORY VARCHAR2(20) NOT NULL,
ID VARCHAR2(20) NOT NULL,
NICKNAME VARCHAR2(20) NOT NULL,
SUBJECT VARCHAR2(20) NOT NULL,
CONTENT CLOB NOT NULL,
FILE1 VARCHAR2(200) NOT NULL,
RE NUMBER DEFAULT 0,
RE_LEV NUMBER DEFAULT 0,
RE_REF NUMBER DEFAULT 0,
RE_SEQ NUMBER DEFAULT 0,
HIT NUMBER DEFAULT 0,
LOGTIME DATE DEFAULT SYSDATE
);

create sequence seq_freenum nocycle nocache;
create sequence seq_freereplynum nocycle nocache;


CREATE TABLE NOTICEBOARD(
SEQ NUMBER NOT NULL,
CATEGORY VARCHAR2(20) NOT NULL,
ID VARCHAR2(20) NOT NULL,
NICKNAME VARCHAR2(20) NOT NULL,
SUBJECT VARCHAR2(20) NOT NULL,
CONTENT CLOB NOT NULL,
FILE1 VARCHAR2(200) NOT NULL,
RE NUMBER DEFAULT 0,
RE_LEV NUMBER DEFAULT 0,
RE_REF NUMBER DEFAULT 0,
RE_SEQ NUMBER DEFAULT 0,
HIT NUMBER DEFAULT 0,
LOGTIME DATE DEFAULT SYSDATE
);

create sequence seq_noticenum nocycle nocache;
create sequence seq_noticereplynum nocycle nocache;

CREATE TABLE QNABOARD(
SEQ NUMBER NOT NULL,
CATEGORY VARCHAR2(20) NOT NULL,
ID VARCHAR2(20) NOT NULL,
NICKNAME VARCHAR2(20) NOT NULL,
SUBJECT VARCHAR2(20) NOT NULL,
CONTENT CLOB NOT NULL,
FILE1 VARCHAR2(200) NOT NULL,
RE NUMBER DEFAULT 0,
RE_LEV NUMBER DEFAULT 0,
RE_REF NUMBER DEFAULT 0,
RE_SEQ NUMBER DEFAULT 0,
HIT NUMBER DEFAULT 0,
LOGTIME DATE DEFAULT SYSDATE
);

create sequence seq_qnanum nocycle nocache;