REM INSERTING into TIP_RECIPE
SET DEFINE OFF;
Insert into TIP_RECIPE (RECIPE_SEQ,ID,NAME,FOODIMAGE,FOODNAME,FOODNAME_DETAIL,COOKINGTIME,DIFFICULTY,JAERYO_NECESSARY,JAERYO_NONECESSARY,RECIPE0,RECIPE1,RECIPE2,RECIPE3,RECIPE4,RECIPE5,RECIPE6,RECIPE7,RECIPE8,RECIPE9,PRICE,HIT,LOGTIME) values (1,'jaesuk','서재석','tomato-pasta1.jpg','토마토 파스타','이것만 있으면 하루 요리 뚝딱',15,1,'마늘 3개, 올리브 오일, 스파게티면, 토마토 소스','null','ㅁㄴㅇㄹ22','ㅁㄴㅇㄹ12','ㅁㄴㅇㄹㄹㄷ32ㄱㄻㄹ','ㄴㅌㅋ','ㅁㄹ','null','null','null','null','null',0,2,to_date('18/04/26','RR/MM/DD'));
Insert into TIP_RECIPE (RECIPE_SEQ,ID,NAME,FOODIMAGE,FOODNAME,FOODNAME_DETAIL,COOKINGTIME,DIFFICULTY,JAERYO_NECESSARY,JAERYO_NONECESSARY,RECIPE0,RECIPE1,RECIPE2,RECIPE3,RECIPE4,RECIPE5,RECIPE6,RECIPE7,RECIPE8,RECIPE9,PRICE,HIT,LOGTIME) values (2,'jaesuk','서재석','740_SAM_0792.JPG','고추장불고기','막걸리 안주로 좋은 것!',25,2,'돼지고기 목살 1kg, 고추장 6큰술, 간장 3큰술, 다진마늘 1과 1/2큰술, 고춧가루 1과 1/2작은술, 올리고당 1큰술, 설탕 1큰술, 참기름 1큰술','양파 1개, 당근 반쪽, 대파 1쪽, 해물(쭈꾸미), 후추 약간, 상추','먹기좋게 썬 돼지고기를 준비한 후
위 레시피에 적혀있는 모든 재료들을 넣어주세요.','고추장 불고기 양념이 잘 밸 수 있도록 골고루 섞어준 후 뚜껑을 덮어 냉장고에 넣습니다.','두 세시간 정도 숙성시간을 주면 됩니다.
(그 이상 반나절 정도 더 두어도 상관없어요.)','당근, 양파, 대파 등을 먹기 좋게 썰어 같이 볶습니다
(경우에 따라 쭈꾸미 등을 넣어도 좋습니다)','다 볶으면 깨를 살살 뿌려 상추에 싸먹습니다.','null','null','null','null','null',15000,58,to_date('18/04/27','RR/MM/DD'));
Insert into TIP_RECIPE (RECIPE_SEQ,ID,NAME,FOODIMAGE,FOODNAME,FOODNAME_DETAIL,COOKINGTIME,DIFFICULTY,JAERYO_NECESSARY,JAERYO_NONECESSARY,RECIPE0,RECIPE1,RECIPE2,RECIPE3,RECIPE4,RECIPE5,RECIPE6,RECIPE7,RECIPE8,RECIPE9,PRICE,HIT,LOGTIME) values (3,'jaesuk','서재석','참치주먹밥.jpg','참치주먹밥','저렴하고 쉽게 구할 수 있는 참치캔을 이용한 주먹밥',20,1,'참치캔 1/2개(50g), 밥 1공기(200g)','null','참치는 체에 밭쳐 기름기를 뺀다. 부추는 송송 썬다.','볼에 밥, 소금, 참기름을 넣고 섞는다.(참치에 간이 되어 있기 때문에 소금간은 약하게 한다.)','밥에 참치, 부추, 검은깨, 후춧가루를 넣고 주걱으로 가르듯이 섞는다.','손에 비닐장갑을 끼고 밥을 한입크기로 동그랗게 만든다.','먹는다','null','null','null','null','null',3000,4,to_date('18/04/27','RR/MM/DD'));
Insert into TIP_RECIPE (RECIPE_SEQ,ID,NAME,FOODIMAGE,FOODNAME,FOODNAME_DETAIL,COOKINGTIME,DIFFICULTY,JAERYO_NECESSARY,JAERYO_NONECESSARY,RECIPE0,RECIPE1,RECIPE2,RECIPE3,RECIPE4,RECIPE5,RECIPE6,RECIPE7,RECIPE8,RECIPE9,PRICE,HIT,LOGTIME) values (4,'user2','김또깡','계란볶음밥.jpg','계란볶음밥','반찬이 없을 때 손쉽게 만드는 볶음밥',15,1,'달걀 2개(100g), 밥 1공기(200g)','null','볼에 달걀, 소금을 넣고 잘 푼다.',' 달군 팬에 식용유 1큰술을 두르고 달걀을 넣고 젓가락으로 저어가며 익혀 스크램블 에그를 만들어 접시에 덜어둔다.','달군 팬에 식용유 1큰술을 두르고 밥을 넣고 고슬고슬하게 볶다가 간장을 넣고 골고루 섞어가며 볶는다.','밥이 다 볶아지면 달걀을 넣고 잘 섞는다.','불을 끄고 참기름, 깨를 넣고 다시 한번 골고루 섞는다.','null','null','null','null','null',3500,52,to_date('18/04/27','RR/MM/DD'));
Insert into TIP_RECIPE (RECIPE_SEQ,ID,NAME,FOODIMAGE,FOODNAME,FOODNAME_DETAIL,COOKINGTIME,DIFFICULTY,JAERYO_NECESSARY,JAERYO_NONECESSARY,RECIPE0,RECIPE1,RECIPE2,RECIPE3,RECIPE4,RECIPE5,RECIPE6,RECIPE7,RECIPE8,RECIPE9,PRICE,HIT,LOGTIME) values (5,'user2','김또깡','null','떡볶이','김또깡님의 추천레시피',20,2,'불린떡 2줌, 어묵 2장, 대파, 멸치 다시마 육수 3.5컵, 고춧가루 2스푼, 설탕 2스푼, 카레가루 2스푼, 진간장 2스푼, 고추장 3스푼','후추,  모짜렐라 치즈','고춧가루, 설탕, 카레가루, 진간장, 고추장을 섞는다.','어묵, 대파, 양파, 깻잎 등을 썬다.','멸치육수를 끓인 후 양념장을 넣어 풀어준다.','밀떡을 넣고, 보글보글 끓기 시작하면 어묵을 넣는다.','떡이 익고 양념이 배기 시작하면 대파를 넣는다.','후추를 기호에 따라 넣는다.
플레이팅한다.','기호에 따라 치즈를 전자레인지에 넣고 돌린다.','null','null','null',0,5,to_date('18/04/27','RR/MM/DD'));
Insert into TIP_RECIPE (RECIPE_SEQ,ID,NAME,FOODIMAGE,FOODNAME,FOODNAME_DETAIL,COOKINGTIME,DIFFICULTY,JAERYO_NECESSARY,JAERYO_NONECESSARY,RECIPE0,RECIPE1,RECIPE2,RECIPE3,RECIPE4,RECIPE5,RECIPE6,RECIPE7,RECIPE8,RECIPE9,PRICE,HIT,LOGTIME) values (8,'hello','박안녕','IMG_2574.jpg','소갈비찜','부드럽고 씹는 식감이 매력적인 소갈비찜',200,3,'소갈비 1.2kg, 당근 1개, 무 1/3, 버섯한줄, 대파 1대, 홍고추 1개, 간장 6스푼, 맛술 4스푼, 설탕 3스푼, 올리고당 3스푼, 다진마늘 1큰술, 참기름, 후추','null','소갈비는 3시간 이상 핏물을 빼주세요.
그 사이 당근과 무는 모서리를 둥글게 만들어 썰어놓으세요.','양념장을 만들어놓으세요. 위 재료에서 간장 6스푼 부터가 모두 양념재료입니다.','핏물 뺀 소고기를 살짝 데쳐서 준비해주세요.
데친후에 찬물에 행궈 준비 ! 데친 갈비는 다시 채소들과 함께 오랫동안 끓여줄거랍니다.','물8컵을 넣고 데친 소갈비와 양파, 대파를 넣고 센불에서 1시간정도 삶아주세요 .','1시간 이상 삶은 소갈비는 건져 칼집을 내거나 크기가 큰 경우는 잘라서 준비하고 삶은물은 버리지 마시고 체에 걸러 3컵정도 분량을 남겨주세요','1시간 이상 삶은 갈비는 건져 만들어둔 소갈비찜 양념장에 30분정도 재워주세요 . ','이후 삶은 국물 3컵을 넣고 센불에서 20분정도 팔팔 끓여주세요. 센불에 보글보글 20분 ! 채소 넣고 15분 !','무와 당근이 푹 - 익어야 하며 소갈비찜에 고루고루 양념이 쏙쏙 베어들어 부드러운 소갈비찜이 완성 되었습니다.','null','null',35000,0,to_date('18/04/27','RR/MM/DD'));
Insert into TIP_RECIPE (RECIPE_SEQ,ID,NAME,FOODIMAGE,FOODNAME,FOODNAME_DETAIL,COOKINGTIME,DIFFICULTY,JAERYO_NECESSARY,JAERYO_NONECESSARY,RECIPE0,RECIPE1,RECIPE2,RECIPE3,RECIPE4,RECIPE5,RECIPE6,RECIPE7,RECIPE8,RECIPE9,PRICE,HIT,LOGTIME) values (9,'hello','박안녕','DSC07345.JPG','소고기미역국','해장용으로 딱이에요!',30,2,'불린 미역, 소고기, 참기름, 국간장, 다진 마늘','소금(국간장 대신)','미역을 먹을 만큼의 양을 불에 불려주고
소고기는 키친타월을 이용해 핏기를 닦아줍니다.','잘 불린 미역과, 핏기 제거된 소고기를 달군 냄비에 넣고
참기름 2수저 넣어 달달 볶아주세요. 소고기 겉면이 익을 때까지 볶아 주세요.','물은 1리터 정도 붓고 보글보글 끓여줍니다.','국간장 또는 소금으로 간을 맞춰줍니다.다진 마늘도 넣어주고 소고기 미역국을 끓이면서 불순물을 제거해 줍니다.','보글보글 끓이다가 중불로 줄여 푹~ 끓여주세요','드세요','null','null','null','null',6000,55,to_date('18/04/27','RR/MM/DD'));
Insert into TIP_RECIPE (RECIPE_SEQ,ID,NAME,FOODIMAGE,FOODNAME,FOODNAME_DETAIL,COOKINGTIME,DIFFICULTY,JAERYO_NECESSARY,JAERYO_NONECESSARY,RECIPE0,RECIPE1,RECIPE2,RECIPE3,RECIPE4,RECIPE5,RECIPE6,RECIPE7,RECIPE8,RECIPE9,PRICE,HIT,LOGTIME) values (13,'hong','홍홍','tip_계란볶음밥_20180501-21-41-35.jpg','sdfas','sadfas',11,1,'asdfas','sdfasf','asfasfasd','fasdf','fasf','fasfsa','fasfas','null','null','null','null','null',11000,5,to_date('18/05/01','RR/MM/DD'));
